### ISSUE TITLE
"discard 2 cards" fails to parse.

### ISSUE THREAD

**Issue by MichaelEbert** [wordbots/wordbots-parser#31]
"discard a card" works.
"discard 2 cards" fails to parse.

comparatively,
"Draw a card" works.
"Draw 2 cards" works.

**Comment by AlexNisnevich** [comment]
"Discard 2 cards" is not feasible to implement right now, unfortunately, because we don't yet have a mechanism for selecting multiple targets for a card. "Discard 2 random cards" ought to work, though.
